version: '2'

services:
  netdata:
    image: titpetric/netdata
    container_name: netdata_netdata
    hostname: 'YourHostname'
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_PTRACE

  nginx:
    build:
      context: nginx/
    container_name: netdata_nginx
    volumes:
      - ./nginx/netdata.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd:/etc/nginx/conf.d/htpasswd
    ports:
      - 82:80
    links:
      - netdata:netdata
    depends_on:
      - netdata
